CREATE PROCEDURE [dbo].[FACTDATA_IN]
AS BEGIN
INSERT INTO FACT.FACTDATA 
	(
		ID
	,	PARENTID
	,	MEASUREUNITID
	,	UNITID
	,	N1_ID
	,	N2_ID
	,	NAME
	,	YEAR
	,	VALUE
	,	ATTRIBUTEID
	,	AGGREGATEID
	,	SUBJECT_ID
	,	TOPSUBJECT_ID
	,	DIMVARIABLES_ID
	)
SELECT
	F.ID AS ID
,	S.ID AS PARENTID
,	F.MEASUREUNITID
,	F.UNITID
,	C.ID AS N1_ID
,	SC.ID AS N2_ID
,	F.NAME
,	F.YEAR
,	F.VALUE
,	F.ATTRIBUTEID
,	F.AGGREGATEID
,	S.ID AS SUBJECT_ID
,	T.ID AS TOPSUBJECT_ID
,	DV.Id AS DIMVARIABLES_ID
FROM
	BDL.FACTDATA F
,	TEMP.DATA_TMP V
,	BDL.DimVariables DV
,	BDL.DIMSUBJECTS S
,	BDL.DIMTOPSUBJECTS T
,	FACT.CATEGORY C
,	FACT.SUBCATEGORY SC
WHERE
	F.ID=V.VARIABLEID
AND V.parentId=DV.Id
AND	DV.PARENTID=S.ID
AND S.PARENTID=T.ID
AND	C.N1=F.N1
AND	SC.N2=F.N2
AND F.ID NOT IN (SELECT ID FROM FACT.FactData)
END
