CREATE TABLE [staging].[databyvariable](
	[Id] INT NOT NULL,
	[parentId] [nvarchar](10) NOT NULL,
	[MEASUREUNITID] [INT],
	[UNITID] [NVARCHAR](30) NULL,
	[N1] [NVARCHAR](255),
	[N2] [NVARCHAR](255),
	[NAME] [NVARCHAR](255) NULL,
	[YEAR] [INT],
	[VALUE][NVARCHAR](255) NULL,
	[ATTRIBUTEID] [INT],
	[AGGREGATEID] [INT]
	)
GO


ALTER TABLE [staging].[databyvariable]  WITH CHECK ADD  CONSTRAINT [DATA_HAS_MEASURE] FOREIGN KEY([MEASUREUNITID])
REFERENCES [staging].[MEASURES] ([Id])
GO

ALTER TABLE [staging].[databyvariable]  WITH CHECK ADD  CONSTRAINT [DATA_HAS_ATTRIBUTE] FOREIGN KEY([ATTRIBUTEID])
REFERENCES [staging].[ATTRIBUTES] ([Id])
GO

ALTER TABLE [staging].[databyvariable]  WITH CHECK ADD  CONSTRAINT [DATA_HAS_UNIT] FOREIGN KEY([UNITID])
REFERENCES [staging].[Units] ([Id])
GO

ALTER TABLE [staging].[databyvariable] CHECK CONSTRAINT [DATA_HAS_UNIT]
GO